name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest openai
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests and capture logs
      run: pytest > test_output.log || true  # Verhindert, dass der Workflow bei einem Fehler stoppt
    - name: Upload log file for analysis
      uses: actions/upload-artifact@v2
      with:
        name: test-logs
        path: test_output.log
    - name: Analyze Logs
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python analyze_logs.py test_output.log

